//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace smART.Integration.LeadsOnline.LeadsOnlineWCF {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    // CODEGEN: The optional WSDL extension element 'PolicyReference' from namespace 'http://schemas.xmlsoap.org/ws/2004/09/policy' was not handled.
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ticketScrapWSSoap_ticketScrapWSSoap", Namespace="http://www.leadsonline.com/")]
    public partial class ScrapContract : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback CheckLoginOperationCompleted;
        
        private System.Threading.SendOrPostCallback SubmitTransactionOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateTransactionOperationCompleted;
        
        private System.Threading.SendOrPostCallback CheckDoNotBuyOperationCompleted;
        
        private System.Threading.SendOrPostCallback CheckDoNotBuy2OperationCompleted;
        
        private System.Threading.SendOrPostCallback UploadImageOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteImageOperationCompleted;
        
        private System.Threading.SendOrPostCallback SetNoTransactionDayForStoreOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ScrapContract() {
            this.Url = global::smART.Integration.LeadsOnline.Properties.Settings.Default.smART_Integration_LeadsOnline_LeadsOnlineWCF_ScrapContract;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event CheckLoginCompletedEventHandler CheckLoginCompleted;
        
        /// <remarks/>
        public event SubmitTransactionCompletedEventHandler SubmitTransactionCompleted;
        
        /// <remarks/>
        public event UpdateTransactionCompletedEventHandler UpdateTransactionCompleted;
        
        /// <remarks/>
        public event CheckDoNotBuyCompletedEventHandler CheckDoNotBuyCompleted;
        
        /// <remarks/>
        public event CheckDoNotBuy2CompletedEventHandler CheckDoNotBuy2Completed;
        
        /// <remarks/>
        public event UploadImageCompletedEventHandler UploadImageCompleted;
        
        /// <remarks/>
        public event DeleteImageCompletedEventHandler DeleteImageCompleted;
        
        /// <remarks/>
        public event SetNoTransactionDayForStoreCompletedEventHandler SetNoTransactionDayForStoreCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.leadsonline.com/CheckLogin", RequestNamespace="http://www.leadsonline.com/", ResponseNamespace="http://www.leadsonline.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Response CheckLogin(LoginInfo login) {
            object[] results = this.Invoke("CheckLogin", new object[] {
                        login});
            return ((Response)(results[0]));
        }
        
        /// <remarks/>
        public void CheckLoginAsync(LoginInfo login) {
            this.CheckLoginAsync(login, null);
        }
        
        /// <remarks/>
        public void CheckLoginAsync(LoginInfo login, object userState) {
            if ((this.CheckLoginOperationCompleted == null)) {
                this.CheckLoginOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCheckLoginOperationCompleted);
            }
            this.InvokeAsync("CheckLogin", new object[] {
                        login}, this.CheckLoginOperationCompleted, userState);
        }
        
        private void OnCheckLoginOperationCompleted(object arg) {
            if ((this.CheckLoginCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CheckLoginCompleted(this, new CheckLoginCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.leadsonline.com/SubmitTransaction", RequestNamespace="http://www.leadsonline.com/", ResponseNamespace="http://www.leadsonline.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Response SubmitTransaction(LoginInfo login, Ticket ticket) {
            object[] results = this.Invoke("SubmitTransaction", new object[] {
                        login,
                        ticket});
            return ((Response)(results[0]));
        }
        
        /// <remarks/>
        public void SubmitTransactionAsync(LoginInfo login, Ticket ticket) {
            this.SubmitTransactionAsync(login, ticket, null);
        }
        
        /// <remarks/>
        public void SubmitTransactionAsync(LoginInfo login, Ticket ticket, object userState) {
            if ((this.SubmitTransactionOperationCompleted == null)) {
                this.SubmitTransactionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSubmitTransactionOperationCompleted);
            }
            this.InvokeAsync("SubmitTransaction", new object[] {
                        login,
                        ticket}, this.SubmitTransactionOperationCompleted, userState);
        }
        
        private void OnSubmitTransactionOperationCompleted(object arg) {
            if ((this.SubmitTransactionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SubmitTransactionCompleted(this, new SubmitTransactionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.leadsonline.com/UpdateTransaction", RequestNamespace="http://www.leadsonline.com/", ResponseNamespace="http://www.leadsonline.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Response UpdateTransaction(LoginInfo login, TicketKey oldTicket, Ticket ticket) {
            object[] results = this.Invoke("UpdateTransaction", new object[] {
                        login,
                        oldTicket,
                        ticket});
            return ((Response)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateTransactionAsync(LoginInfo login, TicketKey oldTicket, Ticket ticket) {
            this.UpdateTransactionAsync(login, oldTicket, ticket, null);
        }
        
        /// <remarks/>
        public void UpdateTransactionAsync(LoginInfo login, TicketKey oldTicket, Ticket ticket, object userState) {
            if ((this.UpdateTransactionOperationCompleted == null)) {
                this.UpdateTransactionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateTransactionOperationCompleted);
            }
            this.InvokeAsync("UpdateTransaction", new object[] {
                        login,
                        oldTicket,
                        ticket}, this.UpdateTransactionOperationCompleted, userState);
        }
        
        private void OnUpdateTransactionOperationCompleted(object arg) {
            if ((this.UpdateTransactionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateTransactionCompleted(this, new UpdateTransactionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.leadsonline.com/CheckDoNotBuy", RequestNamespace="http://www.leadsonline.com/", ResponseNamespace="http://www.leadsonline.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public DoNotBuyInfo[] CheckDoNotBuy(string ID, LoginInfo login, string state) {
            object[] results = this.Invoke("CheckDoNotBuy", new object[] {
                        ID,
                        login,
                        state});
            return ((DoNotBuyInfo[])(results[0]));
        }
        
        /// <remarks/>
        public void CheckDoNotBuyAsync(string ID, LoginInfo login, string state) {
            this.CheckDoNotBuyAsync(ID, login, state, null);
        }
        
        /// <remarks/>
        public void CheckDoNotBuyAsync(string ID, LoginInfo login, string state, object userState) {
            if ((this.CheckDoNotBuyOperationCompleted == null)) {
                this.CheckDoNotBuyOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCheckDoNotBuyOperationCompleted);
            }
            this.InvokeAsync("CheckDoNotBuy", new object[] {
                        ID,
                        login,
                        state}, this.CheckDoNotBuyOperationCompleted, userState);
        }
        
        private void OnCheckDoNotBuyOperationCompleted(object arg) {
            if ((this.CheckDoNotBuyCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CheckDoNotBuyCompleted(this, new CheckDoNotBuyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.leadsonline.com/CheckDoNotBuy2", RequestNamespace="http://www.leadsonline.com/", ResponseNamespace="http://www.leadsonline.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public DoNotBuyInfo[] CheckDoNotBuy2(string BirthDate, string ID, string Name, LoginInfo login) {
            object[] results = this.Invoke("CheckDoNotBuy2", new object[] {
                        BirthDate,
                        ID,
                        Name,
                        login});
            return ((DoNotBuyInfo[])(results[0]));
        }
        
        /// <remarks/>
        public void CheckDoNotBuy2Async(string BirthDate, string ID, string Name, LoginInfo login) {
            this.CheckDoNotBuy2Async(BirthDate, ID, Name, login, null);
        }
        
        /// <remarks/>
        public void CheckDoNotBuy2Async(string BirthDate, string ID, string Name, LoginInfo login, object userState) {
            if ((this.CheckDoNotBuy2OperationCompleted == null)) {
                this.CheckDoNotBuy2OperationCompleted = new System.Threading.SendOrPostCallback(this.OnCheckDoNotBuy2OperationCompleted);
            }
            this.InvokeAsync("CheckDoNotBuy2", new object[] {
                        BirthDate,
                        ID,
                        Name,
                        login}, this.CheckDoNotBuy2OperationCompleted, userState);
        }
        
        private void OnCheckDoNotBuy2OperationCompleted(object arg) {
            if ((this.CheckDoNotBuy2Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CheckDoNotBuy2Completed(this, new CheckDoNotBuy2CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.leadsonline.com/UploadImage", RequestNamespace="http://www.leadsonline.com/", ResponseNamespace="http://www.leadsonline.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Response UploadImage(Image img, int itemIndex, LoginInfo login, TicketKey ticketKey) {
            object[] results = this.Invoke("UploadImage", new object[] {
                        img,
                        itemIndex,
                        login,
                        ticketKey});
            return ((Response)(results[0]));
        }
        
        /// <remarks/>
        public void UploadImageAsync(Image img, int itemIndex, LoginInfo login, TicketKey ticketKey) {
            this.UploadImageAsync(img, itemIndex, login, ticketKey, null);
        }
        
        /// <remarks/>
        public void UploadImageAsync(Image img, int itemIndex, LoginInfo login, TicketKey ticketKey, object userState) {
            if ((this.UploadImageOperationCompleted == null)) {
                this.UploadImageOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUploadImageOperationCompleted);
            }
            this.InvokeAsync("UploadImage", new object[] {
                        img,
                        itemIndex,
                        login,
                        ticketKey}, this.UploadImageOperationCompleted, userState);
        }
        
        private void OnUploadImageOperationCompleted(object arg) {
            if ((this.UploadImageCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UploadImageCompleted(this, new UploadImageCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.leadsonline.com/DeleteImage", RequestNamespace="http://www.leadsonline.com/", ResponseNamespace="http://www.leadsonline.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Response DeleteImage(string filename, ImageCategory imageCategory, int itemIndex, LoginInfo login, TicketKey ticketKey) {
            object[] results = this.Invoke("DeleteImage", new object[] {
                        filename,
                        imageCategory,
                        itemIndex,
                        login,
                        ticketKey});
            return ((Response)(results[0]));
        }
        
        /// <remarks/>
        public void DeleteImageAsync(string filename, ImageCategory imageCategory, int itemIndex, LoginInfo login, TicketKey ticketKey) {
            this.DeleteImageAsync(filename, imageCategory, itemIndex, login, ticketKey, null);
        }
        
        /// <remarks/>
        public void DeleteImageAsync(string filename, ImageCategory imageCategory, int itemIndex, LoginInfo login, TicketKey ticketKey, object userState) {
            if ((this.DeleteImageOperationCompleted == null)) {
                this.DeleteImageOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteImageOperationCompleted);
            }
            this.InvokeAsync("DeleteImage", new object[] {
                        filename,
                        imageCategory,
                        itemIndex,
                        login,
                        ticketKey}, this.DeleteImageOperationCompleted, userState);
        }
        
        private void OnDeleteImageOperationCompleted(object arg) {
            if ((this.DeleteImageCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteImageCompleted(this, new DeleteImageCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.leadsonline.com/SetNoTransactionDayForStore", RequestNamespace="http://www.leadsonline.com/", ResponseNamespace="http://www.leadsonline.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Response SetNoTransactionDayForStore(string TransactionDate, LoginInfo login) {
            object[] results = this.Invoke("SetNoTransactionDayForStore", new object[] {
                        TransactionDate,
                        login});
            return ((Response)(results[0]));
        }
        
        /// <remarks/>
        public void SetNoTransactionDayForStoreAsync(string TransactionDate, LoginInfo login) {
            this.SetNoTransactionDayForStoreAsync(TransactionDate, login, null);
        }
        
        /// <remarks/>
        public void SetNoTransactionDayForStoreAsync(string TransactionDate, LoginInfo login, object userState) {
            if ((this.SetNoTransactionDayForStoreOperationCompleted == null)) {
                this.SetNoTransactionDayForStoreOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSetNoTransactionDayForStoreOperationCompleted);
            }
            this.InvokeAsync("SetNoTransactionDayForStore", new object[] {
                        TransactionDate,
                        login}, this.SetNoTransactionDayForStoreOperationCompleted, userState);
        }
        
        private void OnSetNoTransactionDayForStoreOperationCompleted(object arg) {
            if ((this.SetNoTransactionDayForStoreCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SetNoTransactionDayForStoreCompleted(this, new SetNoTransactionDayForStoreCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.leadsonline.com/")]
    public partial class LoginInfo {
        
        private int storeIdField;
        
        private string userNameField;
        
        private string passwordField;
        
        /// <remarks/>
        public int storeId {
            get {
                return this.storeIdField;
            }
            set {
                this.storeIdField = value;
            }
        }
        
        /// <remarks/>
        public string userName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
            }
        }
        
        /// <remarks/>
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.leadsonline.com/")]
    public partial class DoNotBuyInfo {
        
        private string agencyField;
        
        private string idField;
        
        private string stateField;
        
        private string nameField;
        
        private string dobField;
        
        private string contactNameField;
        
        private string contactNumberField;
        
        /// <remarks/>
        public string agency {
            get {
                return this.agencyField;
            }
            set {
                this.agencyField = value;
            }
        }
        
        /// <remarks/>
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string state {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
            }
        }
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string dob {
            get {
                return this.dobField;
            }
            set {
                this.dobField = value;
            }
        }
        
        /// <remarks/>
        public string contactName {
            get {
                return this.contactNameField;
            }
            set {
                this.contactNameField = value;
            }
        }
        
        /// <remarks/>
        public string contactNumber {
            get {
                return this.contactNumberField;
            }
            set {
                this.contactNumberField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.leadsonline.com/")]
    public partial class Item {
        
        private string makeField;
        
        private string modelField;
        
        private string serialNumberField;
        
        private string descriptionField;
        
        private double amountField;
        
        private string itemStatusField;
        
        private Image[] imagesField;
        
        private bool isVoidField;
        
        private string employeeField;
        
        private double weightField;
        
        private PropertyValue[] extraItemField;
        
        /// <remarks/>
        public string make {
            get {
                return this.makeField;
            }
            set {
                this.makeField = value;
            }
        }
        
        /// <remarks/>
        public string model {
            get {
                return this.modelField;
            }
            set {
                this.modelField = value;
            }
        }
        
        /// <remarks/>
        public string serialNumber {
            get {
                return this.serialNumberField;
            }
            set {
                this.serialNumberField = value;
            }
        }
        
        /// <remarks/>
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public double amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
            }
        }
        
        /// <remarks/>
        public string itemStatus {
            get {
                return this.itemStatusField;
            }
            set {
                this.itemStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public Image[] images {
            get {
                return this.imagesField;
            }
            set {
                this.imagesField = value;
            }
        }
        
        /// <remarks/>
        public bool isVoid {
            get {
                return this.isVoidField;
            }
            set {
                this.isVoidField = value;
            }
        }
        
        /// <remarks/>
        public string employee {
            get {
                return this.employeeField;
            }
            set {
                this.employeeField = value;
            }
        }
        
        /// <remarks/>
        public double weight {
            get {
                return this.weightField;
            }
            set {
                this.weightField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public PropertyValue[] extraItem {
            get {
                return this.extraItemField;
            }
            set {
                this.extraItemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.leadsonline.com/")]
    public partial class Image {
        
        private ImageCategory imageCategoryField;
        
        private ImageType imageTypeField;
        
        private byte[] imageDataField;
        
        /// <remarks/>
        public ImageCategory imageCategory {
            get {
                return this.imageCategoryField;
            }
            set {
                this.imageCategoryField = value;
            }
        }
        
        /// <remarks/>
        public ImageType imageType {
            get {
                return this.imageTypeField;
            }
            set {
                this.imageTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] imageData {
            get {
                return this.imageDataField;
            }
            set {
                this.imageDataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.leadsonline.com/")]
    public enum ImageCategory {
        
        /// <remarks/>
        Customer,
        
        /// <remarks/>
        CustomerID,
        
        /// <remarks/>
        Thumbprint,
        
        /// <remarks/>
        Signature,
        
        /// <remarks/>
        Item,
        
        /// <remarks/>
        Vehicle,
        
        /// <remarks/>
        VehicleLicense,
        
        /// <remarks/>
        Document,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.leadsonline.com/")]
    public enum ImageType {
        
        /// <remarks/>
        Jpeg,
        
        /// <remarks/>
        Png,
        
        /// <remarks/>
        Gif,
        
        /// <remarks/>
        Pdf,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.leadsonline.com/")]
    public partial class PropertyValue {
        
        private string nameField;
        
        private string valueField;
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.leadsonline.com/")]
    public partial class Vehicle {
        
        private string makeField;
        
        private string modelField;
        
        private string yearField;
        
        private string licenseField;
        
        private string stateField;
        
        private string colorField;
        
        /// <remarks/>
        public string make {
            get {
                return this.makeField;
            }
            set {
                this.makeField = value;
            }
        }
        
        /// <remarks/>
        public string model {
            get {
                return this.modelField;
            }
            set {
                this.modelField = value;
            }
        }
        
        /// <remarks/>
        public string year {
            get {
                return this.yearField;
            }
            set {
                this.yearField = value;
            }
        }
        
        /// <remarks/>
        public string license {
            get {
                return this.licenseField;
            }
            set {
                this.licenseField = value;
            }
        }
        
        /// <remarks/>
        public string state {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
            }
        }
        
        /// <remarks/>
        public string color {
            get {
                return this.colorField;
            }
            set {
                this.colorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.leadsonline.com/")]
    public partial class Customer {
        
        private string nameField;
        
        private string fnameField;
        
        private string lnameField;
        
        private string address1Field;
        
        private string address2Field;
        
        private string cityField;
        
        private string stateField;
        
        private string postalCodeField;
        
        private string phoneField;
        
        private string idTypeField;
        
        private string idNumberField;
        
        private string idType2Field;
        
        private string idNumber2Field;
        
        private string dobField;
        
        private int weightField;
        
        private int heightField;
        
        private string eyeColorField;
        
        private string hairColorField;
        
        private string raceField;
        
        private string sexField;
        
        private string remarksField;
        
        private Image[] imagesField;
        
        private Vehicle vehicleField;
        
        private PropertyValue[] extraCustomerField;
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string fname {
            get {
                return this.fnameField;
            }
            set {
                this.fnameField = value;
            }
        }
        
        /// <remarks/>
        public string lname {
            get {
                return this.lnameField;
            }
            set {
                this.lnameField = value;
            }
        }
        
        /// <remarks/>
        public string address1 {
            get {
                return this.address1Field;
            }
            set {
                this.address1Field = value;
            }
        }
        
        /// <remarks/>
        public string address2 {
            get {
                return this.address2Field;
            }
            set {
                this.address2Field = value;
            }
        }
        
        /// <remarks/>
        public string city {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        public string state {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
            }
        }
        
        /// <remarks/>
        public string postalCode {
            get {
                return this.postalCodeField;
            }
            set {
                this.postalCodeField = value;
            }
        }
        
        /// <remarks/>
        public string phone {
            get {
                return this.phoneField;
            }
            set {
                this.phoneField = value;
            }
        }
        
        /// <remarks/>
        public string idType {
            get {
                return this.idTypeField;
            }
            set {
                this.idTypeField = value;
            }
        }
        
        /// <remarks/>
        public string idNumber {
            get {
                return this.idNumberField;
            }
            set {
                this.idNumberField = value;
            }
        }
        
        /// <remarks/>
        public string idType2 {
            get {
                return this.idType2Field;
            }
            set {
                this.idType2Field = value;
            }
        }
        
        /// <remarks/>
        public string idNumber2 {
            get {
                return this.idNumber2Field;
            }
            set {
                this.idNumber2Field = value;
            }
        }
        
        /// <remarks/>
        public string dob {
            get {
                return this.dobField;
            }
            set {
                this.dobField = value;
            }
        }
        
        /// <remarks/>
        public int weight {
            get {
                return this.weightField;
            }
            set {
                this.weightField = value;
            }
        }
        
        /// <remarks/>
        public int height {
            get {
                return this.heightField;
            }
            set {
                this.heightField = value;
            }
        }
        
        /// <remarks/>
        public string eyeColor {
            get {
                return this.eyeColorField;
            }
            set {
                this.eyeColorField = value;
            }
        }
        
        /// <remarks/>
        public string hairColor {
            get {
                return this.hairColorField;
            }
            set {
                this.hairColorField = value;
            }
        }
        
        /// <remarks/>
        public string race {
            get {
                return this.raceField;
            }
            set {
                this.raceField = value;
            }
        }
        
        /// <remarks/>
        public string sex {
            get {
                return this.sexField;
            }
            set {
                this.sexField = value;
            }
        }
        
        /// <remarks/>
        public string remarks {
            get {
                return this.remarksField;
            }
            set {
                this.remarksField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public Image[] images {
            get {
                return this.imagesField;
            }
            set {
                this.imagesField = value;
            }
        }
        
        /// <remarks/>
        public Vehicle vehicle {
            get {
                return this.vehicleField;
            }
            set {
                this.vehicleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public PropertyValue[] extraCustomer {
            get {
                return this.extraCustomerField;
            }
            set {
                this.extraCustomerField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.leadsonline.com/")]
    public partial class TicketKey {
        
        private string ticketnumberField;
        
        private string ticketDateTimeField;
        
        /// <remarks/>
        public string ticketnumber {
            get {
                return this.ticketnumberField;
            }
            set {
                this.ticketnumberField = value;
            }
        }
        
        /// <remarks/>
        public string ticketDateTime {
            get {
                return this.ticketDateTimeField;
            }
            set {
                this.ticketDateTimeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.leadsonline.com/")]
    public partial class Ticket {
        
        private TicketKey keyField;
        
        private string redeemByDateField;
        
        private Customer customerField;
        
        private Item[] itemsField;
        
        private bool isVoidField;
        
        private PropertyValue[] extraTicketField;
        
        /// <remarks/>
        public TicketKey key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        public string redeemByDate {
            get {
                return this.redeemByDateField;
            }
            set {
                this.redeemByDateField = value;
            }
        }
        
        /// <remarks/>
        public Customer customer {
            get {
                return this.customerField;
            }
            set {
                this.customerField = value;
            }
        }
        
        /// <remarks/>
        public Item[] items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
        
        /// <remarks/>
        public bool isVoid {
            get {
                return this.isVoidField;
            }
            set {
                this.isVoidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public PropertyValue[] extraTicket {
            get {
                return this.extraTicketField;
            }
            set {
                this.extraTicketField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.leadsonline.com/")]
    public partial class Response {
        
        private int errorCodeField;
        
        private string errorResponseField;
        
        /// <remarks/>
        public int errorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
            }
        }
        
        /// <remarks/>
        public string errorResponse {
            get {
                return this.errorResponseField;
            }
            set {
                this.errorResponseField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void CheckLoginCompletedEventHandler(object sender, CheckLoginCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CheckLoginCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CheckLoginCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Response Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Response)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void SubmitTransactionCompletedEventHandler(object sender, SubmitTransactionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SubmitTransactionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SubmitTransactionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Response Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Response)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void UpdateTransactionCompletedEventHandler(object sender, UpdateTransactionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateTransactionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateTransactionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Response Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Response)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void CheckDoNotBuyCompletedEventHandler(object sender, CheckDoNotBuyCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CheckDoNotBuyCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CheckDoNotBuyCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DoNotBuyInfo[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DoNotBuyInfo[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void CheckDoNotBuy2CompletedEventHandler(object sender, CheckDoNotBuy2CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CheckDoNotBuy2CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CheckDoNotBuy2CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DoNotBuyInfo[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DoNotBuyInfo[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void UploadImageCompletedEventHandler(object sender, UploadImageCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UploadImageCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UploadImageCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Response Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Response)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void DeleteImageCompletedEventHandler(object sender, DeleteImageCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeleteImageCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeleteImageCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Response Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Response)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void SetNoTransactionDayForStoreCompletedEventHandler(object sender, SetNoTransactionDayForStoreCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SetNoTransactionDayForStoreCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SetNoTransactionDayForStoreCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Response Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Response)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591