<?xml version="1.0" encoding="utf-8"?>
<!--// NotificationWF-->
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
xmlns:msxsl="urn:schemas-microsoft-com:xslt" exclude-result-prefixes="msxsl">
  <xsl:output method="html" indent="no"/>

  <xsl:variable name="newline">
    <xsl:text>&#10;</xsl:text>
  </xsl:variable>

  <xsl:variable name="tab">
    <xsl:text>&#x09;</xsl:text>
  </xsl:variable>

  <xsl:param name="CustomerName"/>
  <xsl:param name="EntityID"/>
  <xsl:param name="CompanyName"/>
  <xsl:param name="UserName"/>
  <xsl:param name="BookingID"/>
  <xsl:param name="SOID"/>
  <xsl:template match="/">
    <html>
      <div>
        <xsl:text>Dear Customer,</xsl:text>
        <br/>
        <br/>
        <xsl:text>Please find attached the image/s of Container# </xsl:text>
        <xsl:value-of select="$EntityID"/>
        <xsl:text> for Booking# </xsl:text>
        <xsl:value-of select="$BookingID"/>
        <xsl:text> and SO# </xsl:text>
        <xsl:value-of select="$SOID"/>
        <xsl:text>. The attached file has been compressed into ".zip" format. Please reach out to </xsl:text>
        <b>
          <xsl:value-of select="$CompanyName"/>
        </b>
        <xsl:text> in case of any questions.</xsl:text>
        <br/>
        <br/>
        <xsl:text>Regards,</xsl:text>
        <br/>
        <br/>
        <b>
          <xsl:value-of select="$CompanyName"/>
        </b>
        <br/>
        <br/>
        <br/>
        <br/>
        <xsl:text>Generated By: </xsl:text>
        <xsl:value-of select="$UserName"/>
      </div>
    </html>
  </xsl:template>
</xsl:stylesheet>
